name: Build, Test, and Deploy Flask App

on:
  push:
    branches:
      - main  # Run the workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Tests
      - name: Run Tests
        run: |
          pytest  # Make sure you have pytest configured for your project

      # Step 5: Deploy to EC2
      - name: Deploy to EC2
        env: 
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          IP_ADDRESS: ${{ secrets.EC2_HOST }}
          USER_NAME: ${{ secrets.EC2_USER }}
        run: | 
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${IP_ADDRESS} '

            # Now we have got the access of EC2 and we will start the deploy .
            cd /home/ubuntu/ &&
            rm -rf SCA_Devops_Python_Project
            git clone https://github.com/maryjonah/SCA_Devops_Python_Project.git
            cd SCA_Devops_Python_Project
            git checkout master &&
            git reset --hard origin/master &&
            git pull origin master &&
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            flask run --host=0.0.0.0
            '



